version: '3'

services:
  app-awcbf:
    build: .
    container_name: app-awcbf
    restart: always
    volumes:
      - ./app:/app
    environment:
      VIRTUAL_HOST: corpus.fulfills.jp
      LETSENCRYPT_HOST: corpus.fulfills.jp
      LETSENCRYPT_EMAIL: web@ksugahara.com
    networks:
      - nginx-network
      - fasttext-vector-api

networks:
  nginx-network:
    external: true
  fasttext-vector-api:
    external: true